import re
import os
import shutil
import platform

# Fungsi untuk memeriksa sistem operasi dan file crontab
def cek_sistem_dan_file():
    # Mendeteksi sistem operasi user
    if platform.system() != 'Linux':
        print("Skrip ini hanya dapat dijalankan pada sistem operasi Linux.")
        return False

    # Mendeteksi file crontab
    if os.path.exists('/etc/crontab'):
        # Jika file backup belum ada, lakukan backup
        if not os.path.exists('/etc/crontab.bak'):
            shutil.copy2('/etc/crontab', '/etc/crontab.bak')
            print("File crontab telah dibackup.")
        # Menambahkan kalimat ke baris paling bawah file crontab
        with open('/etc/crontab', 'r') as file:
            if '# generated by mikfiles' in file.read():
                print("Kalimat sudah ada di file crontab.")
            else:
                # Menambahkan kalimat ke baris paling bawah file crontab jika belum ada
                with open('/etc/crontab', 'a') as file:
                    file.write("\n# generated by mikfiles\n")
                print("Kalimat telah ditambahkan ke baris paling bawah file crontab.")
    else:
        # Jika file crontab tidak ada, buat file baru
        with open('/etc/crontab', 'w') as file:
            file.write("# generated by mikfiles\n")
        print("File crontab baru telah dibuat.")

    return True

# Fungsi untuk menganalisis dan menjelaskan baris konfigurasi cron
def jelaskan_cron():
    try:
        with open('/etc/crontab', 'r') as file:
            # Menambahkan variabel penghitung
            counter = 1
            for line in file:
                # Memeriksa apakah baris tidak dimulai dengan "#" dan bukan baris kosong
                if not line.strip().startswith('#') and line.strip():
                    parts = line.split()
                    # Memeriksa apakah baris memiliki setidaknya 6 bagian (menit, jam, hari dari bulan, bulan, hari dari minggu, perintah)
                    if len(parts) >= 6:
                        # Menampilkan konfigurasi cron asli
                        print(f"Konfigurasi Cron Asli {counter}: {line.strip()}")
                        # Mengganti karakter '*' dengan '-' dalam bagian waktu
                        waktu = ' '.join(part if part != '*' else '-' for part in parts[:5])
                        # Menjelaskan waktu jadwal cron
                        waktu_jelaskan = f"Menit: {parts[0].replace('*', '-')}, Jam: {parts[1].replace('*', '-')}, Hari dari bulan: {parts[2].replace('*', '-')}, Bulan: {parts[3].replace('*', '-')}, Hari dari minggu: {parts[4].replace('*', '-')}"
                        # Menjelaskan perintah yang akan dijalankan
                        perintah = ' '.join(parts[5:])
                        print(f"{counter}. {waktu_jelaskan}, Perintah: {perintah}")
                        # Meningkatkan penghitung
                        counter += 1
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")


# Fungsi untuk menampilkan menu dan memproses pilihan pengguna
def tampilkan_menu():
    print("\nMenu:")
    print("1. Add   2. Edit    3. Delete   4. Disable")
    pilihan = input("Masukkan pilihan Anda (1-4): ")
    return pilihan

# Fungsi untuk menambahkan baris konfigurasi cron
def tambahkan_cron():
    # Menerima input dari pengguna
    menit = input("Masukkan menit (0-59 atau *): ")
    jam = input("Masukkan jam (0-23 atau *): ")
    hari_dari_bulan = input("Masukkan hari dari bulan (1-31 atau *): ")
    bulan = input("Masukkan bulan (1-12 atau *): ")
    hari_dari_minggu = input("Masukkan hari dari minggu (0-7 dimana 0 dan 7 adalah Minggu, atau *): ")
    perintah = input("Masukkan perintah yang ingin dijalankan: ")

    # Membuat baris konfigurasi cron
    cron_baru = f"{menit} {jam} {hari_dari_bulan} {bulan} {hari_dari_minggu} {perintah}\n"

    try:
        with open('/etc/crontab', 'a') as file:
            file.write(cron_baru)
        print("Konfigurasi cron berhasil ditambahkan.")
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")

# Fungsi untuk mengedit baris konfigurasi cron
"""
[NOTE] Bug disini. Ternyata Pada saat saya memilih edit. kemudian saya 
diarahkan untuk memasukkan nomor skrip yang ingin diedit, dan saya 
memilih nomor 5. Namun ternyata skrip menulis konfigurasi cron pada 
baris ke 5, bukan nomor 5 yang saya inginkan yaitu 
= Konfigurasi Cron Asli 5: 15 7 * * * admin python3 /path/2/script.py
"""
def edit_cron():
    # Menerima input dari pengguna
    nomor_konfigurasi = int(input("Masukkan nomor konfigurasi cron yang ingin Anda edit: "))

    # Membaca file crontab dan menyimpan barisnya
    with open('/etc/crontab', 'r') as file:
        baris = file.readlines()

    # Mengambil konfigurasi cron lama
    parts = baris[nomor_konfigurasi - 1].split()
    menit_lama, jam_lama, hari_dari_bulan_lama, bulan_lama, hari_dari_minggu_lama, *perintah_lama = parts
    perintah_lama = ' '.join(perintah_lama)

    # Menerima input baru dari pengguna, atau menggunakan nilai lama jika pengguna hanya menekan enter
    menit = input(f"Masukkan menit baru (0-59 atau *, tekan enter untuk tidak mengubah): ") or menit_lama
    jam = input(f"Masukkan jam baru (0-23 atau *, tekan enter untuk tidak mengubah): ") or jam_lama
    hari_dari_bulan = input(f"Masukkan hari dari bulan baru (1-31 atau *, tekan enter untuk tidak mengubah): ") or hari_dari_bulan_lama
    bulan = input(f"Masukkan bulan baru (1-12 atau *, tekan enter untuk tidak mengubah): ") or bulan_lama
    hari_dari_minggu = input(f"Masukkan hari dari minggu baru (0-7 dimana 0 dan 7 adalah Minggu, atau *, tekan enter untuk tidak mengubah): ") or hari_dari_minggu_lama
    perintah = input(f"Masukkan perintah baru yang ingin dijalankan (tekan enter untuk tidak mengubah): ") or perintah_lama

    # Mengubah baris konfigurasi cron yang dipilih
    baris[nomor_konfigurasi - 1] = f"{menit} {jam} {hari_dari_bulan} {bulan} {hari_dari_minggu} {perintah}\n"

    # Menulis kembali baris ke file crontab
    with open('/etc/crontab', 'w') as file:
        file.writelines(baris)

    print("Konfigurasi cron berhasil diedit.")

# Fungsi untuk menghapus baris konfigurasi cron
def hapus_cron():
    # Implementasi fungsi ini tergantung pada kebutuhan spesifik Anda
    pass

# Fungsi untuk menonaktifkan baris konfigurasi cron
def nonaktifkan_cron():
    # Implementasi fungsi ini tergantung pada kebutuhan spesifik Anda
    pass

def main():
    # Memeriksa sistem operasi dan file crontab
    if not cek_sistem_dan_file():
        return
    # Menampilkan penjelasan baris konfigurasi cron
    jelaskan_cron()
    # Menampilkan menu
    pilihan = tampilkan_menu()
    if pilihan == '1':
        tambahkan_cron()
    elif pilihan == '2':
        edit_cron()
    elif pilihan == '3':
        hapus_cron()
    elif pilihan == '4':
        nonaktifkan_cron()
    else:
        print("Pilihan tidak valid. Silakan coba lagi.")

if __name__ == "__main__":
    main()