import re
import os
import shutil
import platform

# Fungsi untuk memeriksa sistem operasi dan file crontab
def cek_sistem_dan_file():
    # Mendeteksi sistem operasi user
    if platform.system() != 'Linux':
        print("Skrip ini hanya dapat dijalankan pada sistem operasi Linux.")
        return False

    # Mendeteksi file crontab
    if os.path.exists('/etc/crontab'):
        # Jika file backup belum ada, lakukan backup
        if not os.path.exists('/etc/crontab.bak'):
            shutil.copy2('/etc/crontab', '/etc/crontab.bak')
            print("File crontab telah dibackup.")
        # Menambahkan kalimat ke baris paling bawah file crontab
        with open('/etc/crontab', 'r') as file:
            if '# generated by mikfiles' in file.read():
                print("Kalimat sudah ada di file crontab.")
            else:
                # Menambahkan kalimat ke baris paling bawah file crontab jika belum ada
                with open('/etc/crontab', 'a') as file:
                    file.write("\n# generated by mikfiles\n")
                print("Kalimat telah ditambahkan ke baris paling bawah file crontab.")
    else:
        # Jika file crontab tidak ada, buat file baru
        with open('/etc/crontab', 'w') as file:
            file.write("# generated by mikfiles\n")
        print("File crontab baru telah dibuat.")

    return True

# Fungsi untuk menganalisis dan menjelaskan baris konfigurasi cron
def jelaskan_cron():
    konfigurasi_cron = []  # Daftar untuk menyimpan baris konfigurasi cron
    try:
        with open('/etc/crontab', 'r') as file:
            for line in file:
                if not line.strip().startswith('#') and line.strip():
                    konfigurasi_cron.append(line.strip())  # Menambahkan baris konfigurasi cron ke daftar
                    parts = line.split()
                    #if len(parts) < 6:
                    #    print(f"Baris konfigurasi cron tidak lengkap: {line.strip()}")
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")
    return konfigurasi_cron


# Fungsi untuk menampilkan menu dan memproses pilihan pengguna
def tampilkan_menu():
    print("\nMenu:")
    print("1. Add   2. Edit    3. Delete   4. Disable")
    pilihan = input("Masukkan pilihan Anda (1-4): ")
    return pilihan

# Fungsi untuk menambahkan baris konfigurasi cron
def tambahkan_cron():
    # Menerima input dari pengguna
    menit = input("Masukkan menit (0-59 atau *): ")
    jam = input("Masukkan jam (0-23 atau *): ")
    hari_dari_bulan = input("Masukkan hari dari bulan (1-31 atau *): ")
    bulan = input("Masukkan bulan (1-12 atau *): ")
    hari_dari_minggu = input("Masukkan hari dari minggu (0-7 dimana 0 dan 7 adalah Minggu, atau *): ")
    perintah = input("Masukkan perintah yang ingin dijalankan: ")

    # Membuat baris konfigurasi cron
    cron_baru = f"{menit} {jam} {hari_dari_bulan} {bulan} {hari_dari_minggu} {perintah}\n"

    try:
        with open('/etc/crontab', 'a') as file:
            file.write(cron_baru)
        print(f"\033[32m" + "[*]" + "\033[0m" + " Konfigurasi cron berhasil ditambahkan.")
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")

#fungsi untuk edit baris konfigurasi cron
def edit_cron(konfigurasi_cron):
    nomor_konfigurasi = int(input("Masukkan nomor konfigurasi cron yang ingin Anda edit: "))
    if 1 <= nomor_konfigurasi <= len(konfigurasi_cron):
        parts = konfigurasi_cron[nomor_konfigurasi - 1].split()
        if len(parts) >= 6:
            menit_lama, jam_lama, hari_dari_bulan_lama, bulan_lama, hari_dari_minggu_lama, *perintah_lama = parts
            perintah_lama = ' '.join(perintah_lama)
        else:
            menit_lama = jam_lama = hari_dari_bulan_lama = bulan_lama = hari_dari_minggu_lama = '*'
            perintah_lama = ' '.join(parts)
        
        menit = input(f"Masukkan menit baru (0-59 atau *, tekan enter untuk tidak mengubah): ") or menit_lama
        jam = input(f"Masukkan jam baru (0-23 atau *, tekan enter untuk tidak mengubah): ") or jam_lama
        hari_dari_bulan = input(f"Masukkan hari dari bulan baru (1-31 atau *, tekan enter untuk tidak mengubah): ") or hari_dari_bulan_lama
        bulan = input(f"Masukkan bulan baru (1-12 atau *, tekan enter untuk tidak mengubah): ") or bulan_lama
        hari_dari_minggu = input(f"Masukkan hari dari minggu baru (0-7 dimana 0 dan 7 adalah Minggu, atau *, tekan enter untuk tidak mengubah): ") or hari_dari_minggu_lama
        perintah = input(f"Masukkan perintah baru yang ingin dijalankan (tekan enter untuk tidak mengubah): ") or perintah_lama
        konfigurasi_cron[nomor_konfigurasi - 1] = f"{menit} {jam} {hari_dari_bulan} {bulan} {hari_dari_minggu} {perintah}"
        with open('/etc/crontab', 'w') as file:
            for konfigurasi in konfigurasi_cron:
                file.write(f"{konfigurasi}\n")
        print(f"\033[32m" + "[*]" + "\033[0m" + " Konfigurasi cron berhasil diedit.")
    else:
        print(f"\033[31m" + "[!]" + "\033[0m" + " Nomor konfigurasi cron tidak valid.")

# Fungsi untuk menghapus baris konfigurasi cron
def hapus_cron():
    # Implementasi fungsi ini tergantung pada kebutuhan spesifik Anda
    pass

# Fungsi untuk menonaktifkan baris konfigurasi cron
def nonaktifkan_cron():
    # Implementasi fungsi ini tergantung pada kebutuhan spesifik Anda
    pass

def jelaskan_konfigurasi_cron(konfigurasi):
    bagian = konfigurasi.split()
    if len(bagian) >= 6:
        menit, jam, hari_dari_bulan, bulan, hari_dari_minggu, *perintah = bagian
        perintah = ' '.join(perintah)
        
        # Ganti '*' dengan '-'
        if menit == '*': menit = '-'
        if jam == '*': jam = '-'
        if hari_dari_bulan == '*': hari_dari_bulan = '-'
        if bulan == '*': bulan = '-'
        if hari_dari_minggu == '*': hari_dari_minggu = '-'
        
        print(f"[*] Time = Menit: {menit}, Jam: {jam}, Hari dari bulan: {hari_dari_bulan}, Bulan: {bulan}, Hari dari minggu: {hari_dari_minggu}")
        print(f"[*] Commands = {perintah}")
    else:
        print(f"\033[31m" + "[!]" + "\033[0m" + " Konfigurasi cron tidak valid.")


def main():
    konfigurasi_cron = jelaskan_cron()
    for i, konfigurasi in enumerate(konfigurasi_cron, start=1):
        print(f"\033[34m" + f"[{i}]" + "\033[0m" + f" Konfigurasi Cron Asli : {konfigurasi}")
        jelaskan_konfigurasi_cron(konfigurasi)
    pilihan = tampilkan_menu()
    print(f"Pilihan Anda: {pilihan}")  # Tambahkan baris ini
    if pilihan == '1':
        tambahkan_cron()
    elif pilihan == '2':
        edit_cron(konfigurasi_cron)
    elif pilihan == '3':
        hapus_cron()
    elif pilihan == '4':
        nonaktifkan_cron()
    else:
        print(f"\033[31m" + "[!]" + "\033[0m" + " Pilihan tidak valid. Silakan coba lagi.")

if __name__ == "__main__":
    main()